todos/todos/config/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.contrib import admin

from django.views.generic.base import RedirectView, TemplateView

urlpatterns = [
    # Core URLs
    url(r'^', include('core.urls', namespace='core')),

    # Accounts URLs
    # https://github.com/fusionbox/django-authtools/blob/master/authtools/urls.py
    url(r'^', include('extensions.authtools.urls')),

    # Root-level redirects for common browser requests
    url(r'^favicon\.ico$', RedirectView.as_view(url=settings.STATIC_URL + 'img/compressed/favicon.ico'), name='favicon.ico'),
    url(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain'), name='robots.txt'),

    # Admin URLs
    url(r'^admin/rq/', include('extensions.django_rq.urls')),
    url(r'^admin/rq/scheduler/', include('extensions.rq_scheduler.urls', namespace='rq_scheduler')),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
]

admin.site.site_header = '%s Headquarters' % settings.PROJECT_NAME
admin.site.index_title = 'Base of Operations'

if settings.DEBUG:
    urlpatterns += [
        # Testing 404 and 500 error pages
        url(r'^404/$', TemplateView.as_view(template_name='404.html'), name='404'),
        url(r'^500/$', TemplateView.as_view(template_name='500.html'), name='500'),
    ]

    try:
        from django.conf.urls.static import static
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

        import debug_toolbar
        urlpatterns += [url(r'^__debug__/', include(debug_toolbar.urls))]

    # Should only occur when debug mode is on for production testing
    except ImportError as e:
        import logging
        l = logging.getLogger(__name__)
        l.warning(e)

todos/todos/core/urls.py
from django.conf.urls import url

from .views import home

urlpatterns = [
    url(r'^$', home, name='home'),
]

todos/todos/accounts/models.py
from authtools.models import AbstractNamedUser


class User(AbstractNamedUser):
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name']

todos/todos/templates/accounts/base.html
{% extends "base.html" %}

todos/todos/templates/accounts/login.html
{% extends "accounts/base.html" %}
{% load i18n %}

{% block title %}{% trans "Log In" %}{% endblock %}

{% block content %}
  <section class="form short">
    <h1>{% trans "Log In" %}</h1>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <p class="submitRow">
        <a href="{% url 'password_reset' %}">{% trans "Forgot Password?" %}</a>
        <input type="submit" value="{% trans "Log In" %}" />
      </p>
    </form>
  </section>
{% endblock %}

todos/todos/templates/accounts/logout.html
{% extends "accounts/base.html" %}
{% load i18n %}

{% block title %}{% trans "Log Out" %}{% endblock %}

{% block content %}
  <p>{% trans "Logged Out" %}</p>
{% endblock %}

todos/todos/templates/accounts/password_change.html
{% extends "accounts/base.html" %}
{% load i18n %}

{% block title %}{% trans "Password Change" %}{% endblock %}

{% block content %}
  <h1>{% trans "Password Change" %}</h1>

  <p>{% trans "Please enter your old password, for security's sake, and then enter your new password twice so we can verify you typed it in correctly." %}</p>

  <form method="post">

    {% csrf_token %}
    {{ form.as_p }}

    <a href="{% url 'core:home' %}">{% trans "cancel" %}</a>
    <input type="submit" value="{% trans "Change my password" %}">
  </form>
{% endblock %}

todos/todos/templates/accounts/password_change_done.html
{% extends "accounts/base.html" %}
{% load i18n %}

{% block title %}{% trans "Password Change Successful" %}{% endblock %}

{% block content %}
  <h1>{% trans "Password Change Successful" %}</h1>

  <p>{% trans "Your password was changed." %} <a href="{% url 'core:home' %}">{% trans "Back to homepage" %}</a>.</p>
{% endblock %}

todos/todos/templates/accounts/password_reset.html
{% extends "accounts/base.html" %}
{% load i18n %}

{% block title %}{% trans "Password Reset" %}{% endblock %}

{% block content %}
  <h1>{% trans "Password Reset" %}</h1>

  <p>{% trans "Forgotten your password? Enter your e-mail address below, and we'll e-mail instructions for setting a new one." %}</p>

  <form method="post" action="{% url 'password_reset' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="{% trans "Password reset" %}" />
  </form>
{% endblock %}

todos/todos/templates/accounts/password_reset_complete.html
{% extends "accounts/base.html" %}
{% load i18n %}

{% block title %}{% trans "Password Reset Complete" %}{% endblock %}

{% block content %}
  <h1>{% trans "Password Reset Complete" %}</h1>

  <p>{% trans "Your password has been set. You may go ahead and log in now." %}</p>

  <p><a href="{{ login_url }}">{% trans "Log in" %}</a></p>
{% endblock content %}

todos/todos/templates/accounts/password_reset_confirm.html
{% extends "accounts/base.html" %}
{% load i18n %}

{% block title %}{% trans "Password Reset" %}{% endblock %}

{% block content %}
  <section class="form short">
    {% if validlink %}
      <h1>{% trans "Enter New Password" %}</h1>
      <p>{% trans "Please enter your new password twice so we can verify you typed it in correctly." %}</p>

      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <p class="submitRow"><input type="submit" value="{% trans "Change My Password" %}" /></p>
      </form>
    {% else %}
      <h1>{% trans "Password Reset Unsuccessful" %}</h1>
      <p>{% trans "The password reset link was invalid, possibly because it has already been used.  Please request a new password reset." %}</p>
    {% endif %}
  </section>
{% endblock %}

todos/todos/templates/accounts/password_reset_done.html
{% extends "accounts/base.html" %}
{% load i18n %}

{% block title %}{% trans "Password Reset Successful" %}{% endblock %}

{% block content %}
  <h1>{% trans "Password Reset Successful" %}</h1>

  <p>{% trans "We've e-mailed you instructions for setting your password to the e-mail address you submitted. You should be receiving it shortly." %}</p>
{% endblock %}

todos/todos/templates/accounts/password_reset_email.html
{% load i18n %}
{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your email, in case you've forgotten:" %} {{ user.get_username }}

{% blocktrans %}Thanks for using {{ site_name }}!{% endblocktrans %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}