todos/todos/config/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.contrib import admin

from django.views.generic.base import RedirectView, TemplateView

urlpatterns = [
    # Core URLs
    url(r'^', include('core.urls', namespace='core')),

    # Accounts URLs
    # https://github.com/fusionbox/django-authtools/blob/master/authtools/urls.py
    url(r'^', include('extensions.authtools.urls')),

    # Root-level redirects for common browser requests
    url(r'^favicon\.ico$', RedirectView.as_view(url=settings.STATIC_URL + 'img/compressed/favicon.ico'), name='favicon.ico'),
    url(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain'), name='robots.txt'),

    # Admin URLs
    url(r'^admin/rq/', include('extensions.django_rq.urls')),
    url(r'^admin/rq/scheduler/', include('extensions.rq_scheduler.urls', namespace='rq_scheduler')),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
]

admin.site.site_header = '%s Headquarters' % settings.PROJECT_NAME
admin.site.index_title = 'Base of Operations'

if settings.DEBUG:
    urlpatterns += [
        # Testing 404 and 500 error pages
        url(r'^404/$', TemplateView.as_view(template_name='404.html'), name='404'),
        url(r'^500/$', TemplateView.as_view(template_name='500.html'), name='500'),
    ]

    try:
        from django.conf.urls.static import static
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

        import debug_toolbar
        urlpatterns += [url(r'^__debug__/', include(debug_toolbar.urls))]

    # Should only occur when debug mode is on for production testing
    except ImportError as e:
        import logging
        l = logging.getLogger(__name__)
        l.warning(e)

todos/todos/core/urls.py
from django.conf.urls import url

from .views import home

urlpatterns = [
    url(r'^$', home, name='home'),
]

todos/todos/extensions/rq_scheduler/urls.py
from django.conf.urls import url

from .views import jobs, job_detail, delete_job, enqueue_job, clear_jobs, actions

urlpatterns = [
    url(r'^$', jobs, name='jobs'),
    url(r'^jobs/actions/$', actions, name='actions'),
    url(r'^jobs/clear/$', clear_jobs, name='clear_jobs'),
    url(r'^jobs/(?P<job_id>[-\w]+)/$', job_detail, name='job_detail'),
    url(r'^jobs/(?P<job_id>[-\w]+)/delete/$', delete_job, name='delete_job'),
    url(r'^jobs/(?P<job_id>[-\w]+)/enqueue/$', enqueue_job, name='enqueue_job'),
]

todos/todos/extensions/rq_scheduler/views.py
from __future__ import division

from django.contrib import admin
from django_rq.settings import SHOW_ADMIN_LINK

# Change default admin template to include Redis links
if SHOW_ADMIN_LINK:
    admin.site.index_template = 'rq_scheduler/templates/index.html'

from math import ceil

from django.contrib import messages
from django.contrib.admin.views.decorators import staff_member_required
from django.http import Http404
from django.shortcuts import redirect, render
from django.utils.timezone import make_aware, utc

from rq.job import Job
from rq.exceptions import NoSuchJobError

from django_rq import get_scheduler


# Heavily modified views originally from
# https://github.com/ui/django-rq/blob/master/django_rq/views.py
@staff_member_required
def jobs(request):
    scheduler = get_scheduler()
    jobs_list = scheduler.get_jobs(with_times=True)
    items_per_page = 100
    num_jobs = len(jobs_list)
    page = int(request.GET.get('page', 1))

    if num_jobs > 0:
        last_page = int(ceil(num_jobs / items_per_page))
        page_range = range(1, last_page + 1)
        offset = items_per_page * (page - 1)

        jobs_list = jobs_list[offset:offset + items_per_page]
        for job, scheduled_at in jobs_list:
            job.scheduled_at = make_aware(scheduled_at, utc)
            job.created_at = make_aware(job.created_at, utc)
        jobs = [job for job, scheduled_time in jobs_list]
    else:
        jobs = []
        page_range = []

    context_data = {
        'title': 'Scheduled Jobs',
        'jobs': jobs,
        'num_jobs': num_jobs,
        'page': page,
        'page_range': page_range,
    }
    return render(request, 'rq_scheduler/templates/jobs.html', context_data)


@staff_member_required
def job_detail(request, job_id):
    scheduler = get_scheduler()
    try:
        job = Job.fetch(job_id, connection=scheduler.connection)
    except NoSuchJobError:
        raise Http404("Couldn't find job with this ID: %s" % job_id)

    if job in scheduler:
        jobs_list_with_times = scheduler.get_jobs(with_times=True)
        jobs_list = [j for j, scheduled_at in jobs_list_with_times]
        job.scheduled_at = jobs_list_with_times[jobs_list.index(job)][1]
        job.scheduled_at = make_aware(job.scheduled_at, utc)

    job.created_at = make_aware(job.created_at, utc)
    job.enqueued_at = make_aware(job.enqueued_at, utc) if job.enqueued_at else None

    context_data = {
        'title': 'Job Info',
        'job': job,
    }
    return render(request, 'rq_scheduler/templates/job_detail.html', context_data)


@staff_member_required
def delete_job(request, job_id):
    scheduler = get_scheduler()
    job = Job.fetch(job_id, connection=scheduler.connection)

    if request.method == 'POST':
        job.cancel()
        messages.info(request, 'You have successfully deleted %s' % job.id)
        return redirect('rq_scheduler:jobs')

    context_data = {
        'title': 'Are you sure?',
        'job': job,
    }
    return render(request, 'rq_scheduler/templates/delete_job.html', context_data)


@staff_member_required
def enqueue_job(request, job_id):
    scheduler = get_scheduler()
    job = Job.fetch(job_id, connection=scheduler.connection)

    if request.method == 'POST':
        scheduler.enqueue_job(job)
        messages.info(request, 'You have successfully enqueued %s' % job.id)
        return redirect('rq_scheduler:jobs')

    context_data = {
        'title': 'Are you sure?',
        'job': job,
    }
    return render(request, 'rq_scheduler/templates/enqueue_job.html', context_data)


@staff_member_required
def clear_jobs(request):
    scheduler = get_scheduler()
    if request.method == 'POST':
        for job in scheduler.get_jobs():
            job.cancel()
        messages.info(request, 'You have successfully cleared all scheduled jobs')
        return redirect('rq_scheduler:jobs')

    context_data = {
        'title': 'Are you sure?',
    }
    return render(request, 'rq_scheduler/templates/clear_jobs.html', context_data)


@staff_member_required
def actions(request):
    scheduler = get_scheduler()

    if request.method == 'POST' and request.POST.get('action', False):
        # Confirmation page for selected Action
        if request.POST.get('_selected_action', False):
            context_data = {
                'action': request.POST['action'],
                'job_ids': request.POST.getlist('_selected_action'),
            }
            return render(request, 'rq_scheduler/templates/confirm_action.html', context_data)

        # Performing the actual action
        elif request.POST.get('job_ids', False):
            job_ids = request.POST.getlist('job_ids')

            if request.POST['action'] == 'delete':
                for job_id in job_ids:
                    job = Job.fetch(job_id, connection=scheduler.connection)
                    job.cancel()
                messages.info(request, 'You have successfully deleted %s jobs!' % len(job_ids))
            elif request.POST['action'] == 'enqueue':
                for job_id in job_ids:
                    job = Job.fetch(job_id, connection=scheduler.connection)
                    scheduler.enqueue_job(job)
                messages.info(request, 'You have successfully enqueued %d  jobs!' % len(job_ids))

    return redirect('rq_scheduler:jobs')

todos/todos/extensions/rq_scheduler/templates/clear_jobs.html
{% extends "admin/base_site.html" %}

{% load url from future %}

{% block extrastyle %}
  {{ block.super }}
  <style>
    .data {
      display: inline-block;
      float: left;
      width: 80%;
    }
  </style>
  <link href="{{ STATIC_URL }}admin/css/forms.css" type="text/css" rel="stylesheet">
  {% endblock %}

{% block breadcrumbs %}
  <div class="breadcrumbs">
    <a href="{% url 'admin:index' %}">Home</a> &rsaquo;
    <a href="{% url 'rq_scheduler:jobs' %}">RQ Scheduler</a> &rsaquo;
    Clear All
  </div>
  {% endblock %}

{% block content_title %}<h1>Are you sure?</h1>{% endblock %}

{% block content %}

<div id="content-main">
  <p>
    Are you sure you want to clear all <a href="{% url 'rq_scheduler:jobs' %}">RQ Scheduled Jobs</a>?
    This action can not be undone.
  </p>
  <form action="" method="post">
    {% csrf_token %}
    <div>
      <input type="submit" value="Yes, I'm sure" />
    </div>
  </form>
</div>

{% endblock %}

todos/todos/extensions/rq_scheduler/templates/confirm_action.html
{% extends "admin/base_site.html" %}

{% load url from future %}

{% block extrastyle %}
  {{ block.super }}
  <style>
    .data {
      display: inline-block;
      float: left;
      width: 80%;
    }
  </style>
  <link href="{{ STATIC_URL }}admin/css/forms.css" type="text/css" rel="stylesheet">
  {% endblock %}

{% block breadcrumbs %}
  <div class="breadcrumbs">
    <a href="{% url 'admin:index' %}">Home</a> &rsaquo;
    <a href="{% url 'rq_scheduler:jobs' %}">RQ Scheduler</a> &rsaquo;
    {{ action|capfirst }}
  </div>
  {% endblock %}

{% block content_title %}<h1>Are you sure?</h1>{% endblock %}

{% block content %}

<div id="content-main">
  <p>
    Are you sure you want to <b>{{ action|capfirst }}</b> the selected jobs from <a href="{% url 'rq_scheduler:jobs' %}" target="_blank">RQ Scheduled Jobs</a>? These jobs are selected:
  </p>
  <ul>
  {% for job_id in job_ids %}
    <li><a href="{% url 'rq_scheduler:job_detail' job_id %}" target="_blank">{{ job_id }}</a></li>
  {% endfor %}
  </ul>
  <form action="" method="post">
    {% csrf_token %}
    <div>
      {% for job_id in job_ids %}
        <input type="hidden" name="job_ids" value="{{ job_id }}">
      {% endfor %}
      <input type="hidden" name="action" value="{{ action }}" />
      <input type="submit" value="Yes, I'm sure" />
    </div>
  </form>
</div>

{% endblock %}

todos/todos/extensions/rq_scheduler/templates/delete_job.html
{% extends "admin/base_site.html" %}

{% load url from future %}

{% block extrastyle %}
  {{ block.super }}
  <style>
    .data {
      display: inline-block;
      float: left;
      width: 80%;
    }
  </style>
  <link href="{{ STATIC_URL }}admin/css/forms.css" type="text/css" rel="stylesheet">
  {% endblock %}

{% block breadcrumbs %}
  <div class="breadcrumbs">
    <a href="{% url 'admin:index' %}">Home</a> &rsaquo;
    <a href="{% url 'rq_scheduler:jobs' %}">RQ Scheduler</a> &rsaquo;
    <a href="{% url 'rq_scheduler:job_detail' job.id %}">{{ job.id }}</a> &rsaquo;
    Delete
  </div>
  {% endblock %}

{% block content_title %}<h1>Are you sure?</h1>{% endblock %}

{% block content %}

<div id="content-main">
  <p>
    Are you sure you want to delete <a href="{% url 'rq_scheduler:job_detail' job.id %}">{{ job.id }}</a> from <a href="{% url 'rq_scheduler:jobs' %}">RQ Scheduled Jobs</a>?
    This action can not be undone.
  </p>
  <form action="" method="post">
    {% csrf_token %}
    <div>
      <input type="submit" value="Yes, I'm sure" />
    </div>
  </form>
</div>

{% endblock %}

todos/todos/extensions/rq_scheduler/templates/enqueue_job.html
{% extends "admin/base_site.html" %}

{% load url from future %}

{% block extrastyle %}
  {{ block.super }}
  <style>
    .data {
      display: inline-block;
      float: left;
      width: 80%;
    }
  </style>
  <link href="{{ STATIC_URL }}admin/css/forms.css" type="text/css" rel="stylesheet">
  {% endblock %}

{% block breadcrumbs %}
  <div class="breadcrumbs">
    <a href="{% url 'admin:index' %}">Home</a> &rsaquo;
    <a href="{% url 'rq_scheduler:jobs' %}">RQ Scheduler</a> &rsaquo;
    <a href="{% url 'rq_scheduler:job_detail' job.id %}">{{ job.id }}</a> &rsaquo;
    Delete
  </div>
  {% endblock %}

{% block content_title %}<h1>Are you sure?</h1>{% endblock %}

{% block content %}

<div id="content-main">
  <p>
    Are you sure you want to enqueue <a href="{% url 'rq_scheduler:job_detail' job.id %}">{{ job.id }}</a> immediately and have it perform?
    This action can not be undone.
  </p>
  <form action="" method="post">
    {% csrf_token %}
    <div>
      <input type="submit" value="Yes, I'm sure" />
    </div>
  </form>
</div>

{% endblock %}

todos/todos/extensions/rq_scheduler/templates/index.html
{% extends "admin/index.html" %}

{% load url from future %}

{% block sidebar %}

  {{ block.super }}

  <div style="clear: both"></div>
  <h1 style="margin-top: 15px">Redis Apps</h1>

  <div id="django-rq" style="float: left">
    <div class="module">
      <table style="width: 498px">
        <caption>Django RQ</caption>
        <tbody>
          <tr>
            <th>
              <a href="{% url 'rq_home' %}">
                Queues
              </a>
            </th>
          </tr>
        </tbody>
      </table>
    </div>
  </div>

  <div id="rq-scheduler" style="float: left">
    <div class="module">
      <table style="width: 498px">
        <caption>RQ Scheduler</caption>
        <tbody>
          <tr>
            <th>
              <a href="{% url 'rq_scheduler:jobs' %}">
                Scheduled Jobs
              </a>
            </th>
          </tr>
        </tbody>
      </table>
    </div>
  </div>

  {% endblock %}

todos/todos/extensions/rq_scheduler/templates/job_detail.html
{% extends "admin/base_site.html" %}

{% load url from future %}

{% block extrastyle %}
  {{ block.super }}
  <style>
    .data {
      display: inline-block;
      float: left;
      width: 80%;
      font-size: 12px;
      padding-top: 3px;
    }
  </style>
  <link href="{{ STATIC_URL }}admin/css/forms.css" type="text/css" rel="stylesheet">
  {% endblock %}

{% block breadcrumbs %}
  <div class="breadcrumbs">
    <a href="{% url 'admin:index' %}">Home</a> &rsaquo;
    <a href="{% url 'rq_scheduler:jobs' %}">RQ Scheduler</a> &rsaquo;
    <a href="{% url 'rq_scheduler:job_detail' job.id %}">{{ job.id }}</a>
  </div>
  {% endblock %}

{% block content_title %}<h1>Job Info</h1>{% endblock %}

{% block content %}

<div id="content-main">

  <fieldset class="module aligned ">

    <div class="form-row">
      <div>
        <label class="required">ID:</label>
        <div class="data">{{ job.id }}</div>
      </div>
    </div>

    <div class="form-row">
      <div>
        <label class="required">Queue:</label>
        <div class="data">{{ job.origin }}</div>
      </div>
    </div>

    <div class="form-row">
      <div>
        <label class="required">Timeout:</label>
        <div class="data">{{ job.timeout }}</div>
      </div>
    </div>

    <div class="form-row">
      <div>
        <label class="required">Result TTL:</label>
        <div class="data">{{ job.result_ttl }}</div>
      </div>
    </div>

    <div class="form-row">
      <div>
        <label class="required">Created:</label>
        <div class="data">{{ job.created_at }} ({{ job.created_at|timesince }} ago)</div>
      </div>
    </div>

    <div class="form-row">
      <div>
        <label class="required">Scheduled:</label>
        <div class="data">
          {% if job.scheduled_at %}
            {{ job.scheduled_at }} (in {{ job.scheduled_at|timeuntil }})
          {% else %}
            Queued
          {% endif %}
        </div>
      </div>
    </div>

    <div class="form-row">
      <div>
        <label class="required">Queued:</label>
        <div class="data">
          {% if job.enqueued_at %}
            {{ job.enqueued_at }} (in {{ job.enqueued_at|timeuntil }})
          {% else %}
            Not queued yet
          {% endif %}
        </div>
      </div>
    </div>

    <div class="form-row">
      <div>
        <label class="required">Status:</label>
        <div class="data">{{ job.get_status }}</div>
      </div>
    </div>

    <div class="form-row">
      <div>
        <label class="required">Callable:</label>
        <div class="data">{{ job.func_name }}</div>
      </div>
    </div>

    <div class="form-row">
      <div>
        <label class="required">Args:</label>
        <div class="data">
          {% if job.args %}
          <ul>
            {% for arg in job.args %}
              <li>{{ arg }}</li>
            {% endfor %}
          </ul>
          {% endif %}
        </div>
      </div>
    </div>

    <div class="form-row">
      <div>
        <label class="required">Kwargs:</label>
        <div class="data">
          {% if job.kwargs %}
            <ul>
              {% for key, value in job.kwargs.items %}
                <li>{{ key }}: {{ value|escape }}</li>
              {% endfor %}
            </ul>
          {% endif %}
        </div>
      </div>
    </div>

    <div class="form-row">
      <div>
        <label class="required">Exception:</label>
        <div class="data"><pre>{% if job.exc_info %}{{ job.exc_info|linebreaks }}{% endif %}</pre></div>
      </div>
    </div>

  </fieldset>

  <div class="submit-row">
    <p class="deletelink-box"><a href="{% url 'rq_scheduler:delete_job' job.id %}" class="deletelink">Delete</a></p>
    <form method="POST" action="{% url 'rq_scheduler:enqueue_job' job.id %}">
      {% csrf_token %}
      <input type="submit" value="Enqueue" class="default" name="enqueue">
    </form>
  </div>

</div>

{% endblock %}

todos/todos/extensions/rq_scheduler/templates/jobs.html
{% extends "admin/base_site.html" %}

{% load admin_static %}
{% load url from future %}

{% block extrastyle %}
  {{ block.super }}
  <link rel="stylesheet" type="text/css" href="{% static "admin/css/changelists.css" %}">
  {% endblock %}

{% block extrahead %}
  {{ block.super }}
  <script type="text/javascript" src="{% static "admin/js/jquery.js" %}"></script>
  <script type="text/javascript" src="{% static "admin/js/jquery.init.js" %}"></script>
  <script type="text/javascript" src="{% static "admin/js/actions.js" %}"></script>
  <script type="text/javascript">
  (function($) {
    $(document).ready(function($) {
      $("tr input.action-select").actions();
    });
  })(django.jQuery);
  </script>
  {% endblock %}

{% block breadcrumbs %}
  <div class="breadcrumbs">
    <a href="{% url 'admin:index' %}">Home</a> &rsaquo;
    <a href="{% url 'rq_scheduler:jobs' %}">RQ Scheduler</a>
  </div>
  {% endblock %}

{% block content_title %}<h1>Scheduled Jobs</h1>{% endblock %}

{% block content %}

<div id="content-main">
  <ul class="object-tools">
    <li><a href="{% url 'rq_scheduler:clear_jobs' %}" class="deletelink">Clear Scheduled Jobs</a></li>
  </ul>
  <div class="module" id="changelist">
    <form id="changelist-form" action="{% url 'rq_scheduler:actions' %}" method="post">
      {% csrf_token %}
      <div class="actions">
        <label>Actions:
          <select name="action">
            <option value="" selected="selected">---------</option>
            <option value="enqueue">Enqueue</option>
            <option value="delete">Delete</option>
          </select>
        </label>
        <button type="submit" class="button" title="Execute selected action" name="index" value="0">Go</button>
      </div>
      <div class="results">
        <table id="result_list">
          <thead>
            <tr>
              <th scope="col" class="action-checkbox-column">
                <div class="text">
                  <span><input type="checkbox" id="action-toggle" style="display: inline-block;"></span>
                </div>
                <div class="clear"></div>
              </th>
              <th><div class="text"><span>ID</span></div></th>
              <th><div class="text"><span>Created</span></div></th>
              <th><div class="text"><span>Scheduled</span></div></th>
              <th><div class="text"><span>Callable</span></div></th>
              <th><div class="text"><span>Args</span></div></th>
            </tr>
          </thead>
          <tbody>
            {% for job in jobs %}
              <tr class="{% cycle 'row1' 'row2' %}">
                <td class="action-checkbox">
                  <input class="action-select" name="_selected_action" type="checkbox" value="{{ job.id }}">
                </td>
                <th>
                  <a href="{% url 'rq_scheduler:job_detail' job.id %}">
                    {{ job.id }}
                  </a>
                </th>
                <td>{{ job.created_at }}</td>
                <td>{{ job.scheduled_at }}</td>
                <td>{{ job.func_name }}</td>
                <td>
                  {% if job.args %}
                    {% for arg in job.args %}
                      <li>{{ arg }}</li>
                    {% endfor %}
                  {% endif %}
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
      <p class="paginator">
        {% for p in page_range %}
          {% if p == page %}
            <span class="this-page">{{ p }}</span>
          {% elif forloop.last %}
            <a href="?page={{ p }}" class="end">{{ p }}</a>
          {% else %}
            <a href="?page={{ p }}">{{ p }}</a>
          {% endif %}
        {% endfor %}
        {{ num_jobs }} jobs
      </p>
    </form>
  </div>
</div>

{% endblock %}